// This file is generated by Slice Machine. Update with care!

import FraeBackgroundandTitle from './FraeBackgroundandTitle';
import FraeOverview from './FraeOverview';
import FraeTechused from './FraeTechused';
import TrackaBackgroundandTitle from './TrackaBackgroundandTitle';
import TrackaTechused from './TrackaTechused';
import TrackOverview from './TrackOverview';

export {
	FraeBackgroundandTitle,
	FraeOverview,
	FraeTechused,
	TrackaBackgroundandTitle,
	TrackaTechused,
	TrackOverview,
};

export const components = {
	bacgroundw_title: FraeBackgroundandTitle,
	p_frae_overview: FraeOverview,
	techused: FraeTechused,
	tracka_backgroundand_title: TrackaBackgroundandTitle,
	tracka_techused: TrackaTechused,
	track_overview: TrackOverview,
};
